import { z } from 'zod';
import * as schemas from './schemas.js';

export type ConfigInput = z.infer<typeof schemas.configInputSchema>;
export type Config = z.infer<typeof schemas.configSchema>;
export type CrawlConfig = Omit<Config, 'id' | 'createdAt' | 'updatedAt'>;
export type PageSnapshot = z.infer<typeof schemas.pageSnapshotSchema>;
export type RunStatus = z.infer<typeof schemas.runStatusSchema>;
export type Run = z.infer<typeof schemas.runSchema>;
export type Page = z.infer<typeof schemas.pageSchema>;
export type CreateRunInput = z.infer<typeof schemas.createRunSchema>;
export type JobDto = z.infer<typeof schemas.jobSchema>;
export type ScenarioStep = z.infer<typeof schemas.scenarioStepSchema>;
export type ScenarioInput = z.infer<typeof schemas.scenarioInputSchema>;
export type Scenario = z.infer<typeof schemas.scenarioSchema>;
export type ScenarioRunStatus = z.infer<typeof schemas.scenarioRunStatusSchema>;
export type ScenarioRunStepResult = z.infer<typeof schemas.scenarioRunStepResultSchema>;
export type ScenarioRunResult = z.infer<typeof schemas.scenarioRunResultSchema>;
export type ScenarioRun = z.infer<typeof schemas.scenarioRunSchema>;
export type CreateScenarioRunInput = z.infer<typeof schemas.createScenarioRunSchema>;
export type ApiEndpointInput = z.infer<typeof schemas.apiEndpointInputSchema>;
export type ApiEndpoint = z.infer<typeof schemas.apiEndpointSchema>;
export type ApiTestRunStatus = z.infer<typeof schemas.apiTestRunStatusSchema>;
export type ApiTestResult = z.infer<typeof schemas.apiTestResultSchema>;
export type ApiTestRun = z.infer<typeof schemas.apiTestRunSchema>;
export type OpenApiImportInput = z.infer<typeof schemas.openapiImportSchema>;
export type OpenApiImportResponse = z.infer<typeof schemas.openapiImportResponseSchema>;
